---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-system-backend-deployment
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: ecommerce-system-backend
      labels:
        tier: backend
    spec:
      containers:
        - name: ecommerce-system-backend-deployment-container
          image: ngophuocloi/ecommerce-system-backend:azure
          ports:
            - containerPort: 8888
          envFrom:
            - secretRef:
                name:  ecommerce-system-backend-secret
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-system-backend-service
spec:
  ports:
    - port: 80
      targetPort: 8888
  selector:
    tier: backend

