apiVersion: v1
kind: Service
metadata:
  name: ecommerce-system-backend-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30001
  selector:
    tier: backend   